project_id = "jqaghjzyafrfrtsycwci"

[functions.geocode]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.send-sms-code]
verify_jwt = false

[functions.verify-sms-code]
verify_jwt = false
