platforms:
  ios:
    targets:
      App:
        # Push Notifications capability
        entitlements:
          - aps-environment: development  # Change to 'production' for App Store
        
        # Info.plist settings
        plist:
          - file: Info.plist
            entries:
              # Push notifications background mode
              - UIBackgroundModes: [remote-notification]
              
              # Deep link URL scheme
              - CFBundleURLTypes:
                - CFBundleURLSchemes:
                  - babagu
                - CFBundleURLName: com.websko.babagu
              
  android:
    manifest:
      - file: AndroidManifest.xml
        target: manifest/application/activity
        inject:
          - <intent-filter>
              <action android:name="android.intent.action.VIEW" />
              <category android:name="android.intent.category.DEFAULT" />
              <category android:name="android.intent.category.BROWSABLE" />
              <data android:scheme="babagu" />
            </intent-filter>
